image: starlabio/ubuntu-native-build:1.0.7

cache:
    paths:
        - target/

stages:
    - format
    - build
    - test

.format: &format-template
    stage: format
    script:
        - echo "CRATE_DIR=$CRATE_DIR"
        - cd $CRATE_DIR
        - cargo fmt -- --write-mode=diff

format-libxenstore:
    variables:
        CRATE_DIR: libxenstore
    <<: *format-template

format-rxenstored:
    variables:
        CRATE_DIR: rxenstored
    <<: *format-template

build:x86:
    stage: build
    script:
        - pushd libxenstore
        - cargo build --verbose
        - popd
        - pushd rxenstored
        - cargo build --verbose

build:aarch64:
    stage: build
    script:
        - export CC=aarch64-linux-gnu-gcc
        - export AR=aarch64-linux-gnu-ar
        - export ARCH=arm64
        - pushd libxenstore
        - cargo build --verbose --target=aarch64-unknown-linux-gnu
        - popd
        - pushd rxenstored
        - cargo build --verbose --target=aarch64-unknown-linux-gnu

build:armhf:
    stage: build
    script:
        - export CC=arm-linux-gnueabihf-gcc
        - export AR=arm-linux-gnueabihf-ar
        - export ARCH=arm
        - pushd libxenstore
        - cargo build --verbose --target=arm-unknown-linux-gnueabihf
        - popd
        - pushd rxenstored
        - cargo build --verbose --target=arm-unknown-linux-gnueabihf

test:x86:
    stage: test
    script:
        - pushd libxenstore
        - cargo test
        - popd
        - pushd rxenstored
        - cargo test
