#!/bin/bash

sources=$(git ls-files | grep -E '\.rs$')

status=0

for f in $sources; do
    backup=$f.bk
    rm -f ${backup}

    rustfmt $f
    if [[ -f ${backup} ]]; then
        diff_output=$(diff -u $f $backup)
        echo "File format violation for $f"
        echo "${diff_output}"
        status=1
    fi
done

exit ${status}
